services:
  bulltrackDB:
    image: postgres:15.3
    container_name: bulltrack-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bulltrack-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
